### ISSUE TITLE
[Feature Request] Option to create / delete custom desktop entries of any file

### ISSUE THREAD

**Issue by onlyreportingissues** [edfloreshz/cosmic-tweaks#10]
It will allow those files to be executed from the app library & also to be added to the dock & panel.

**Comment by edfloreshz** [comment]
Looks like you're looking for [this](https://flathub.org/apps/com.github.alexkdeveloper.desktop-files-creator)

**Comment by onlyreportingissues** [comment]
Oh nice that's awesome, thanks.
