### ISSUE TITLE
Feature: App labels and window un-grouping in the dock

### ISSUE THREAD

**Issue by joewood9364** [edfloreshz/cosmic-tweaks#3]
Thanks for starting this project. This feature request would enable app labels and window un-grouping in the dock similar to traditional Windows/KDE layout.

https://github.com/pop-os/cosmic-applets/issues/297
Above is the same request for official COSMIC integration (which would be ideal). However since the Dash To Panel extension implements this functionality in GNOME perhaps similarly COSMIC Tweaks could implement this functionality in COSMIC.

**Comment by edfloreshz** [comment]
Thanks for submitting this feature request!

Unfortunately this is beyond the scope of this project, this app only exposes existing configurations, if there's not an option to do this in [cosmic-settings](https://github.com/pop-os/cosmic-settings) once https://github.com/pop-os/cosmic-applets/issues/297 is merged I'd be happy to add it here.

I'll close this but we can reopen once the PR is merged, sound good?
