### ISSUE TITLE
[Feature Request] Classic Start Menu

### ISSUE THREAD

**Issue by onlyreportingissues** [edfloreshz/cosmic-tweaks#7]
Basically something like Open Shell (for Windows) or Arc Menu (for Linux).

![screenshot_3628_AdN84Ze](https://github.com/edfloreshz/cosmic-tweaks/assets/103491514/e8b9e8ed-01d5-4dcb-a919-cf1ce7d8a63b)

**Comment by edfloreshz** [comment]
This is beyond the scope of this project, this would have to be developed as a separate applet.
