### ISSUE TITLE
[Feature Request] A tab for updating & deleting 3rd party applets

### ISSUE THREAD

**Issue by onlyreportingissues** [edfloreshz/cosmic-tweaks#9]
Basically something like a light version of [Extension Manager](https://github.com/mjakeman/extension-manager).

**Comment by edfloreshz** [comment]
Isn't this already available in COSMIC Settings > Desktop > Desktop and Panel > Panel > Configure panel applets?

**Comment by onlyreportingissues** [comment]
> Isn't this already available in COSMIC Settings > Desktop > Desktop and Panel > Panel > Configure panel applets?

Not sure, but I haven't seen an option that allows me to uninstall nor update a 3rd party applet like [cosmic-applet-places-status-indicator](https://github.com/leb-kuchen/cosmic-applet-places-status-indicator) for example.

**Comment by edfloreshz** [comment]
As far as I know this is a planned feature for cosmic-settings, please ask the S76 devs in Mattermost.

Word of advice, ask them before opening a PR here as this is a project dedicated to exposing settings that will not be available in cosmic-settings.

If cosmic-settings ever implements or ports some of these features, they will be removed from this project.

**Comment by onlyreportingissues** [comment]
Oh ok, sounds good. 👍 I actually asked this on GitHub along the line but got no response yet, so I took it as a no. 😅

**Comment by edfloreshz** [comment]
Mattermost is a better place to ask questions, have that as your first option 👍🏼

I'm closing this for now but we can revisit in the future if needed.
